before_script:
  - export https_proxy=http://m100.cache.pvt:3128
  - export http_proxy=http://m100.cache.pvt:3128
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - composer install --prefer-source --no-interaction
  - memcached -p 11211 -d -u memcache
  - memcached -p 11212 -d -u memcache

test:7.2:
  image: babadzhanyan/cache_php-unit:7.2
  tags:
    - mrgs
  script:
    - php vendor/bin/phpunit --coverage-text --colors=never -c phpunit.xml

# test:7.3:
#   image: php:7.3
#   tags:
#     - mrgs
#   script:
#     - php vendor/bin/phpunit --coverage-text --colors=never -c phpunit.xml

# test:7.4:
#   image: php:7.4
#   tags:
#     - mrgs
#   script:
#     - php vendor/bin/phpunit --coverage-text --colors=never -c phpunit.xml
