language: php

php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1
  - 7.2

services: memcache
env: MEMCACHED__HOST=localhost

before_install:
  - curl -s http://getcomposer.org/installer | php
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - php composer.phar install --prefer-source --no-interaction
  - phpenv rehash

before_script:
  - memcached -p 11211 -d

script:
  - php vendor/bin/phpunit -c phpunit.xml
