language: php

php:
  - 7.2
  - 7.3
  - 7.4

before_install:
  - |
    if [[ $TRAVIS_PHP_VERSION =~ 5.[456] ]]; then
          echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi;
  - |
    if [[ $TRAVIS_PHP_VERSION =~ 7.[012] ]]; then
          echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    fi;
  - phpenv config-rm xdebug.ini
  - echo 'date.timezone = "Europe/Moscow"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - phpenv rehash

install:
  - composer install

before_script:
  - memcached -p 11211 -d
  - memcached -p 11212 -d

script:
  - php vendor/bin/phpunit -c phpunit.xml --no-coverage

#services: memcache