language: php

php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env: MEMCACHED__HOST=localhost

before_install:
  - PHP_INI=~/.phpenv/versions/$(phpenv version-name)/etc/php.ini;
  - |
    if [[ $TRAVIS_PHP_VERSION =~ 5.[56] ]]; then
      echo "extension = memcached.so" >> $PHP_INI;
      echo yes | pecl install apcu-4.0.10;
      echo "apc.enabled = 1" >> $PHP_INI;
      echo "apc.enable_cli = 1" >> $PHP_INI;
      phpenv config-rm xdebug.ini;
    fi;
  - |
    if [[ $TRAVIS_PHP_VERSION =~ 7.[10] ]]; then
      apt-get install -y php-memcached;
      echo "extension = memcached.so" >> $PHP_INI;
      echo yes | pecl install apcu-5.1.2;
      echo "apc.enabled = 1" >> $PHP_INI;
      echo "apc.enable_cli = 1" >> $PHP_INI;
    fi;
  - |
    if [[ $TRAVIS_PHP_VERSION =~ 7.[0] ]]; then
      phpenv config-rm xdebug.ini;
    fi;
  - curl -s http://getcomposer.org/installer | php
  - if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
  - php composer.phar install --prefer-source --no-interaction
  - phpenv rehash

install:
  - composer install

before_script:
  - memcached -p 11211 -d

script:
  - php vendor/bin/phpunit -c phpunit.xml

services: memcache